"use client";

import { formatCurrency } from "@hotel-pricing/shared";
import type { RevenueActionInsightView } from "@hotel-pricing/shared";
import { cn } from "@/lib/utils";
import {
  formatFreshnessRelative,
  formatRevenueActionTypeLabel,
  getRevenueActionSourceMeta,
  isActionDemo,
  isActionLive,
} from "@/lib/revenue-action-display";
import { troskySurfaces, troskyTextClamp } from "./trosky-primitives";
import { RevenueActionSourceBadge } from "./revenue-action-source-badge";
import { TroskyStatusBadge } from "./trosky-status-badge";

function formatOptionalMoney(cents: number | null | undefined): string {
  if (cents == null) return "Not available";
  return formatCurrency(cents);
}

function formatOptionalDate(iso: string | null | undefined): string {
  if (!iso) return "Not available";
  return new Date(iso).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function formatSourceLabel(insight: RevenueActionInsightView): string {
  return getRevenueActionSourceMeta({
    source: insight.source,
    evidenceJson: insight.evidence.raw as Record<string, unknown> | null,
    type: insight.type,
  }).label;
}

function EvidenceRow({
  label,
  value,
  className,
}: {
  label: string;
  value: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "flex min-w-0 flex-col gap-0.5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-4",
        className
      )}
    >
      <dt className="shrink-0 text-xs font-medium uppercase tracking-wide text-muted-foreground">
        {label}
      </dt>
      <dd className={troskyTextClamp("text-sm tabular-nums text-foreground sm:text-right")}>
        {value}
      </dd>
    </div>
  );
}

export interface RevenueActionEvidencePanelProps {
  insight: RevenueActionInsightView;
  showRawEvidence?: boolean;
  className?: string;
}

export function RevenueActionEvidencePanel({
  insight,
  showRawEvidence = false,
  className,
}: RevenueActionEvidencePanelProps) {
  const { evidence } = insight;
  const sourceMeta = getRevenueActionSourceMeta({
    source: insight.source,
    evidenceJson: evidence.raw as Record<string, unknown> | null,
    type: insight.type,
  });
  const compRef =
    evidence.compReferenceCents ?? evidence.compMedianCents ?? null;

  const current =
    insight.currentValueCents ?? evidence.currentRateCents ?? null;
  const recommended =
    insight.recommendedValueCents ?? evidence.recommendedRateCents ?? null;
  const delta = insight.deltaCents ?? evidence.rateDeltaCents ?? null;

  const isWatch = insight.type === "WATCH_DEMAND";
  const isEvent = insight.type === "EVENT_PRICING";
  const isPricing = insight.type === "PRICE_CHANGE";

  const lastEvalRelative = formatFreshnessRelative(insight.lastEvaluatedAt);
  const summaryTitle = isWatch
    ? "Watch summary"
    : isEvent
      ? "Event pricing summary"
      : "Recommendation summary";

  return (
    <div className={cn("min-w-0 space-y-4", className)}>
      {isActionDemo({
        source: insight.source,
        evidenceJson: evidence.raw as Record<string, unknown> | null,
      }) ? (
        <p
          className="rounded-xl border border-amber-200/80 bg-amber-50 px-3 py-2 text-xs leading-relaxed text-amber-950 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200"
          role="note"
        >
          This is demo data used to preview the workflow. It is not live
          system intelligence.
        </p>
      ) : null}

      {isWatch ? (
        <p
          className="rounded-xl border border-border bg-muted/50 px-3 py-2 text-xs leading-relaxed text-muted-foreground"
          role="note"
        >
          This is a watch item, not a rate-change recommendation. Review demand
          signals before changing rates.
        </p>
      ) : null}

      {isActionLive({
        source: insight.source,
        evidenceJson: evidence.raw as Record<string, unknown> | null,
      }) ? (
        <p className="rounded-xl border border-border bg-muted/50 px-3 py-2 text-xs leading-relaxed text-muted-foreground">
          Generated by the recommendation or event demand worker after a Trosky
          recompute.
        </p>
      ) : null}

      {insight.hasLimitedEvidence ? (
        <p className="rounded-xl border border-border bg-muted/50 px-3 py-2 text-xs leading-relaxed text-muted-foreground">
          Limited evidence available. Future worker runs may enrich this action
          with more context.
        </p>
      ) : null}

      <div className={cn(troskySurfaces.mutedPanel, "min-w-0 space-y-4 p-4 sm:p-5")}>
        <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          {summaryTitle}
        </h3>
        <div className="flex min-w-0 flex-wrap items-center gap-2">
          <span className="text-xs font-medium text-foreground">
            {formatRevenueActionTypeLabel(insight.type)}
          </span>
          {insight.stayDate ? (
            <span className="text-sm text-muted-foreground">
              Stay {insight.stayDate}
            </span>
          ) : null}
          <TroskyStatusBadge variant="info">
            {insight.status === "PENDING"
              ? "Pending review"
              : insight.status[0] + insight.status.slice(1).toLowerCase()}
          </TroskyStatusBadge>
        </div>

        {isEvent && evidence.eventName ? (
          <div className="min-w-0 rounded-xl border border-trosky-red/20 bg-trosky-red/5 px-3 py-3">
            <p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
              Event
            </p>
            <p className="mt-1 text-base font-semibold text-foreground">
              {evidence.eventName}
            </p>
            {evidence.eventDaysAway != null ? (
              <p className="mt-1 text-sm text-muted-foreground">
                {evidence.eventDaysAway} day
                {evidence.eventDaysAway === 1 ? "" : "s"} away
              </p>
            ) : null}
          </div>
        ) : null}

        {isPricing || (!isWatch && (current != null || recommended != null)) ? (
          <div className="grid min-w-0 gap-3 sm:grid-cols-3">
            <div className="min-w-0 rounded-xl border border-border bg-background px-3 py-3">
              <p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
                Current rate
              </p>
              <p className="mt-1 text-lg font-semibold tabular-nums text-foreground">
                {formatOptionalMoney(current)}
              </p>
            </div>
            <div className="min-w-0 rounded-xl border border-border bg-background px-3 py-3 text-center">
              <p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
                Suggested change
              </p>
              <p
                className={cn(
                  "mt-1 text-lg font-semibold tabular-nums",
                  delta != null && delta > 0
                    ? "text-trosky-red"
                    : "text-foreground"
                )}
              >
                {delta != null
                  ? `${delta > 0 ? "+" : delta < 0 ? "−" : ""}${formatCurrency(Math.abs(delta))}`
                  : "Not available"}
              </p>
            </div>
            <div className="min-w-0 rounded-xl border border-trosky-red/25 bg-trosky-red/5 px-3 py-3">
              <p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
                Suggested rate
              </p>
              <p className="mt-1 text-lg font-semibold tabular-nums text-foreground">
                {formatOptionalMoney(recommended)}
              </p>
            </div>
          </div>
        ) : null}

        {isWatch && evidence.watchReason ? (
          <p className="text-sm leading-relaxed text-muted-foreground">
            <span className="font-medium text-foreground">Watch reason: </span>
            {evidence.watchReason}
          </p>
        ) : null}
      </div>

      <div className={cn(troskySurfaces.card, "min-w-0 p-4 sm:p-5")}>
        <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Why Trosky surfaced this
        </h3>
        <p className={troskyTextClamp("text-sm font-medium text-foreground")}>
          {insight.explanation.headline}
        </p>
        <p className={troskyTextClamp("mt-2 text-sm leading-relaxed text-muted-foreground")}>
          {insight.explanation.body}
        </p>
        {insight.explanation.bullets.length > 0 ? (
          <ul className="mt-3 min-w-0 list-disc space-y-2 pl-5 text-sm leading-relaxed text-muted-foreground">
            {insight.explanation.bullets.map((bullet, i) => (
              <li key={i} className={troskyTextClamp()}>
                {bullet}
              </li>
            ))}
          </ul>
        ) : null}
        {insight.reason ? (
          <p className={troskyTextClamp("mt-3 border-t border-border/80 pt-3 text-sm text-muted-foreground")}>
            {insight.reason}
          </p>
        ) : null}
      </div>

      <div className={cn(troskySurfaces.card, "min-w-0 p-4 sm:p-5")}>
        <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Evidence
        </h3>
        <p className="mb-3 text-[11px] leading-relaxed text-muted-foreground">
          Comp reference is a competitor benchmark from available scrape data —
          not a guaranteed market median.
        </p>
        <dl className="min-w-0 space-y-3">
          <EvidenceRow label="Comp reference" value={formatOptionalMoney(compRef)} />
          <EvidenceRow
            label="Rate vs comp"
            value={formatOptionalMoney(evidence.rateGapCents)}
          />
          <EvidenceRow
            label="Confidence"
            value={evidence.confidence ?? "Not available"}
          />
          <EvidenceRow
            label="Urgency"
            value={evidence.urgency ?? "Not available"}
          />
          {evidence.demandLevel ? (
            <EvidenceRow label="Demand signal" value={evidence.demandLevel} />
          ) : null}
        </dl>
      </div>

      <div className={cn(troskySurfaces.card, "min-w-0 p-4 sm:p-5")}>
        <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Source and freshness
        </h3>
        <dl className="min-w-0 space-y-3">
          <div className="flex min-w-0 flex-wrap items-center gap-2 pb-1">
            <RevenueActionSourceBadge
              action={{
                source: insight.source,
                evidenceJson: evidence.raw as Record<string, unknown> | null,
                type: insight.type,
              }}
            />
            <span className={troskyTextClamp("text-xs text-muted-foreground")}>
              {sourceMeta.description}
            </span>
          </div>
          <EvidenceRow label="Source" value={formatSourceLabel(insight)} />
          <EvidenceRow
            label="Generated"
            value={formatOptionalDate(evidence.generatedAt)}
          />
          <EvidenceRow
            label="Last evaluated"
            value={
              insight.lastEvaluatedAt
                ? `${formatOptionalDate(insight.lastEvaluatedAt)}${lastEvalRelative ? ` (${lastEvalRelative})` : ""}`
                : "Not available"
            }
          />
          <EvidenceRow
            label="Expires"
            value={formatOptionalDate(insight.expiresAt)}
          />
        </dl>
      </div>

      {insight.estimatedUpsideLowCents != null &&
      insight.estimatedUpsideHighCents != null ? (
        <div className={cn(troskySurfaces.card, "min-w-0 p-4 sm:p-5")}>
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Estimated upside
          </h3>
          <p className="text-sm tabular-nums text-foreground">
            {formatCurrency(insight.estimatedUpsideLowCents)}–
            {formatCurrency(insight.estimatedUpsideHighCents)}
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            Heuristic range from rate delta — estimated, not guaranteed.
          </p>
        </div>
      ) : null}

      {showRawEvidence && evidence.raw != null ? (
        <details className={cn(troskySurfaces.mutedPanel, "min-w-0 p-4 sm:p-5")}>
          <summary className="cursor-pointer text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Raw evidence (analyst only)
          </summary>
          <pre className="mt-3 max-h-48 overflow-auto rounded-lg border border-border bg-muted/50 p-3 text-[11px] leading-relaxed text-foreground">
            {JSON.stringify(evidence.raw, null, 2)}
          </pre>
        </details>
      ) : null}
    </div>
  );
}
