import { formatCurrency } from "@hotel-pricing/shared";
import type {
  RevenueActionInsightEvidence,
  RevenueActionInsightExplanation,
  RevenueActionType,
  ActionConfidence,
} from "@hotel-pricing/shared";
import { isActionDemo } from "@/lib/revenue-action-display";

function appendSharedInsightBullets(
  input: {
    source: string | null;
    evidence: RevenueActionInsightEvidence;
    hasLimitedEvidence: boolean;
  },
  bullets: string[]
): void {
  if (
    isActionDemo({
      source: input.source,
      evidenceJson: input.evidence.raw as Record<string, unknown> | null,
    })
  ) {
    bullets.push(
      "This is demo/seed data used to preview the workflow — not live worker output."
    );
  }

  if (input.hasLimitedEvidence) {
    bullets.push(
      "Limited evidence available. Trosky used what was on hand; competitor/reference details may be missing."
    );
  }
}

function compReferenceCents(
  evidence: RevenueActionInsightEvidence
): number | null {
  if (evidence.compReferenceCents != null) return evidence.compReferenceCents;
  if (evidence.compMedianCents != null) return evidence.compMedianCents;
  return null;
}

export function buildRevenueActionInsightExplanation(input: {
  type: RevenueActionType;
  summary: string;
  reason: string | null;
  confidence: ActionConfidence;
  currentValueCents: number | null;
  recommendedValueCents: number | null;
  deltaCents: number | null;
  source: string | null;
  lastEvaluatedAt: string | null;
  evidence: RevenueActionInsightEvidence;
  hasLimitedEvidence: boolean;
}): RevenueActionInsightExplanation {
  const bullets: string[] = [];
  const compRef = compReferenceCents(input.evidence);

  if (input.type === "PRICE_CHANGE") {
    const headline = "Why Trosky flagged this rate";
    let body =
      "Trosky recommends reviewing this rate because the suggested price differs meaningfully from the current rate";

    if (input.confidence === "HIGH" || input.confidence === "MEDIUM") {
      body += ` and the recommendation confidence is ${input.confidence.toLowerCase()}.`;
    } else {
      body += ".";
    }

    if (input.deltaCents != null && input.deltaCents !== 0) {
      const direction = input.deltaCents > 0 ? "increase" : "decrease";
      bullets.push(
        `Suggested ${direction} of ${formatCurrency(Math.abs(input.deltaCents))} versus the current rate.`
      );
    }

    if (compRef != null && input.currentValueCents != null) {
      const gap = input.currentValueCents - compRef;
      if (gap < 0) {
        bullets.push(
          `The current rate appears below the competitor reference by ${formatCurrency(Math.abs(gap))}.`
        );
      } else if (gap > 0) {
        bullets.push(
          `The current rate is above the competitor reference by ${formatCurrency(gap)}.`
        );
      } else {
        bullets.push("The current rate aligns with the competitor reference.");
      }
    } else {
      bullets.push(
        "Competitor reference data was not available for this action."
      );
    }

    if (input.recommendedValueCents != null) {
      bullets.push(
        `The suggested target is ${formatCurrency(input.recommendedValueCents)}.`
      );
    }

    if (input.source === "RECOMMENDATION") {
      bullets.push(
        "This action was generated by the deterministic recommendation worker."
      );
    } else if (
      input.source === "SEED" ||
      input.source === "seed-demo" ||
      isActionDemo({
        source: input.source,
        evidenceJson: input.evidence.raw as Record<string, unknown> | null,
      })
    ) {
      bullets.push(
        "This action uses seeded demo data for development and design review."
      );
    }

    if (input.lastEvaluatedAt) {
      const when = new Date(input.lastEvaluatedAt).toLocaleString(undefined, {
        dateStyle: "medium",
        timeStyle: "short",
      });
      bullets.push(`This was last evaluated at ${when}.`);
    }

    if (input.reason?.trim()) {
      bullets.push(input.reason.trim());
    } else if (input.summary?.trim()) {
      bullets.push(input.summary.trim());
    }

    appendSharedInsightBullets(input, bullets);
    return { headline, body, bullets };
  }

  if (input.type === "EVENT_PRICING") {
    const headline = "Why Trosky flagged this event";
    const body =
      "Trosky surfaced this because an upcoming event may affect demand for this stay date. Review pricing before the event window tightens.";

    if (input.evidence.eventDaysAway != null) {
      bullets.push(
        `The event is ${input.evidence.eventDaysAway} day${input.evidence.eventDaysAway === 1 ? "" : "s"} away.`
      );
    }
    if (input.evidence.eventName) {
      bullets.push(`Event: ${input.evidence.eventName}.`);
    }
    if (input.evidence.demandLevel) {
      bullets.push(`Demand level signal: ${input.evidence.demandLevel}.`);
    }
    if (compRef != null && input.currentValueCents != null) {
      bullets.push(
        `Current rate ${formatCurrency(input.currentValueCents)} vs comp reference ${formatCurrency(compRef)}.`
      );
    }
    if (input.source === "EVENT_DEMAND") {
      bullets.push(
        "This action was generated by the deterministic event and demand worker."
      );
    }
    if (input.reason?.trim()) bullets.push(input.reason.trim());
    else if (input.summary?.trim()) bullets.push(input.summary.trim());
    appendSharedInsightBullets(input, bullets);

    return { headline, body, bullets };
  }

  if (input.type === "WATCH_DEMAND") {
    const headline = "Why this is a watch item";
    const body =
      "Trosky is not recommending a price change yet. This is a watch item because demand signals may be building.";

    if (input.evidence.watchReason) {
      const reasonLabel =
        input.evidence.watchReason === "event-window"
          ? "Upcoming event in the watch window (8–14 days)."
          : input.evidence.watchReason === "recommendation-below-threshold"
            ? "Recommendation confidence is present, but the rate delta is below the price-change threshold."
            : input.evidence.watchReason;
      bullets.push(reasonLabel);
    }
    if (input.evidence.eventDaysAway != null) {
      bullets.push(
        `Stay date is ${input.evidence.eventDaysAway} day${input.evidence.eventDaysAway === 1 ? "" : "s"} out.`
      );
    }
    if (input.evidence.eventName) {
      bullets.push(`Related: ${input.evidence.eventName}.`);
    }
    if (input.source === "EVENT_DEMAND") {
      bullets.push(
        "This action was generated by the deterministic event and demand worker."
      );
    }
    if (input.reason?.trim()) bullets.push(input.reason.trim());
    else if (input.summary?.trim()) bullets.push(input.summary.trim());
    appendSharedInsightBullets(input, bullets);

    return { headline, body, bullets };
  }

  return {
    headline: "Action insight",
    body: input.summary || "Review this revenue action in context of your hotel strategy.",
    bullets: input.reason ? [input.reason] : [],
  };
}
